version: '3'
services:
  web-ui:
    container_name: web-ui
    image: web-ui
    ports:
      - 80:3000
    restart: on-failure
    environment:
      - REACT_APP_SERVER_BASE=http://192.168.99.100:8080
  minejs-service:
    container_name: service
    image: service
    ports:
      - 8080:8080
    restart: on-failure
#  minejs-server:
#    container_name: minejs-server
#    image: server
#    network_mode: "host"
#    volumes:
#      - ~/world:/opt/minecraft/world
#    restart: on-failure