version: '3'
services:
  web-ui:
    container_name: web-ui
    image: javagrinko-docker-registry.bintray.io/minejs-web-ui
    ports:
      - 80:5000
    restart: on-failure
    environment:
      - REACT_APP_SERVER_BASE=http://ec2-18-188-167-97.us-east-2.compute.amazonaws.com
  minejs-service:
    container_name: service
    image: javagrinko-docker-registry.bintray.io/minejs-service
    ports:
      - 8080:8080
    restart: on-failure
